### ISSUE TITLE
Eine Fehlermeldung erscheint bei der Erstellung der Datenpunkte

### ISSUE THREAD

**Issue by Kenaschon** [slimline33/OpenEPaperLink-IOBROKER-JavaScript#1]
Alles funktioniert soweit. Wirklich tolle Arbeit.

Danke

Der Fehler der Erscheint hattes Du ja schon gepostet.

`javascript.0 (1401318) script.js.EPS.Websocket2_Test: Object "0_userdata.0.OpenEPaperLink.4467090B10421125" can't be copied: {}`

Grüße
Manfred

**Comment by slimline33** [comment]
Danke. Ja, der Fehler erscheint und den bekomme ich auch nicht weg. Ist jedoch nur beim ersten erstellen der Datenpunkte so. Beim aktualisieren bleibt er dann aus. Könnte noch ein Fehler beim erstellen der Ordner sein. Muss ich bei Gelegenheit nochmal angehen.
