### ISSUE TITLE
Ändern des "Zielortes" ?

### ISSUE THREAD

**Issue by Kenaschon** [slimline33/OpenEPaperLink-IOBROKER-JavaScript#2]
Das ist jetzt "meckern" auf hohem Niveau.

Du hast im Skript dieses Ziel fest eingetragen.

`0_userdata.0.OpenEPaperLink`

Ich habe drei APs Jeweils Erd- Ober- und Dachgeschoss.

Entsprechend habe ich die Ziele `0_userdata.0.Tag_Buttons.Erdgeschoss` usw.

Macht es viel Arbeit, das der Zielort der Datenpunkte genauso eingestellt werden kann wie die IP-Adresse des APs?

Also vor dem Satz: `/// AB HIER NICHTS MEHR ÄNDERN!`

Grüße
Manfred

**Comment by slimline33** [comment]
Servus Manfred,

Da die APs ja selber untereinander kommunizieren finde ich es persönlich nicht sinnvoll die Ordner so anzulegen. Du kannst ja von jedem AP aus alle Tags mit Daten beschicken. 

Ich würde mit dem Alias Adapter oder einen Blockly mir die Informationen aus den entsprechenden Datenpunkten ziehen.

Gruß Christoph

**Comment by Kenaschon** [comment]
Hallo Christoph,

das hatte ich am Anfang so. Da hörten die APs aber nicht damit auf sich untereinander die TAGs zuzuschieben". Das ging über zwei Tage das es nur ein hin und her geschiebe war. Es hörte einfach nicht auf.
Deshalb habe ich eine feste Zuordnung der TAGs zu jedem AP. Nun ist Ruhe im System. Jeder AP hat seinen eigenen Kanal.

Grüße
Manfred

**Comment by slimline33** [comment]
Ja. Sie suchen sich jedes mal den stärksten AP aus und wenn diese nah beieinander sind, dann wechseln sie je nach Lust und Laune. Wie Du bereits festgestellt hast, kann man das unterbinden indem man jedem AP seinen eigenen Kanal zuweist. 

Die APs kommunizieren trotzdem über Multicast untereinander und Du kannst nach wie vor die Tags von jedem AP aus beschicken.

**Comment by Kenaschon** [comment]
Das hatte ich auch schon mal probiert. Per Puppeteer ein Bild gemacht und das an  AP(1) geschickt und gewartet, das an an dem TAG der an AP(2) ist ankommt. Hat bis jetzt noch nicht funktioniert.

**Comment by slimline33** [comment]
Ich lasse alles über einen AP machen. Einer hat die 2.52 und der andere eine custom beta. Funktioniert eigentlich sehr gut. Die finden sich aber schon untereinander?

**Comment by Kenaschon** [comment]
Jepp.
